// <auto-generated />
using CustomersTask.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomersTask.Migrations
{
    [DbContext(typeof(customerDbContext))]
    partial class customerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CustomersTask.Models.country", b =>
                {
                    b.Property<int>("countryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("countryName");

                    b.HasKey("countryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CustomersTask.Models.customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<int>("governmentId");

                    b.Property<string>("phone");

                    b.Property<string>("stateMarried");

                    b.Property<string>("street");

                    b.HasKey("Id");

                    b.HasIndex("governmentId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CustomersTask.Models.government", b =>
                {
                    b.Property<int>("governmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("countryId");

                    b.Property<string>("governmentName");

                    b.HasKey("governmentId");

                    b.HasIndex("countryId");

                    b.ToTable("Governments");
                });

            modelBuilder.Entity("CustomersTask.Models.customer", b =>
                {
                    b.HasOne("CustomersTask.Models.government", "Government")
                        .WithMany("Customers")
                        .HasForeignKey("governmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CustomersTask.Models.government", b =>
                {
                    b.HasOne("CustomersTask.Models.country", "Country")
                        .WithMany("Governments")
                        .HasForeignKey("countryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
